name: C
on:
  workflow_dispatch:
  push:
    branches:
  pull_request:
    paths:
      - "c/**"
      - .github/workflows/c.yaml
env:
  LLVM_PATH_WIN: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin"
jobs:
  coverage:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - windows-latest
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup ${{ matrix.os }}
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get -qq update
            sudo apt-get -qq install lcov libeigen3-dev libserialport-dev
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "$LLVM_PATH_WIN" >> $GITHUB_PATH
          fi

      - name: Run tests
        run: make test-c
        env:
          CMAKEFLAGS: -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=true

      - name: Build examples
        run: make -C c/build examples

      - name: Upload coverage to codecov.io
        run: |
          bash <(curl -s https://codecov.io/bash) -s c/build || echo "Codecov did not collect coverage reports";
