name: C
on:
  workflow_dispatch:
  push:
    branches:
  pull_request:
    paths:
      - "c/**"
      - .github/workflows/c.yaml
env:
  LLVM_PATH_WIN: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/Llvm/x64/bin"
jobs:
  coverage:
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - macos-10.15
          - windows-latest
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup ${{ matrix.os }}
        shell: bash
        run: |
          echo 'CMAKEFLAGS=-DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=true' >> $GITHUB_ENV
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get -qq update
            sudo apt-get -qq install lcov libeigen3-dev libserialport-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install pkg-config eigen libserialport
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo 'CMAKEFLAGS=-DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles"' >> $GITHUB_ENV
            choco install eigen
            echo "$LLVM_PATH_WIN" >> $GITHUB_PATH
          fi

      - name: Run tests
        run: make test-c

      - name: Build examples
        if: matrix.os != 'windows-latest'
        run: make -C c/build examples
        env:
          CMAKEFLAGS: -v -DCMAKE_BUILD_TYPE=Debug

      - name: Run install
        run: make install
