name: Build docker image
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - Makefile
      - .github/workflows/docker.yaml
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          mkdir docker-build
          cd docker-build
          docker build --build-arg DOCKER_USER=$USER -f ../Dockerfile -t libsbp-build .
          cd ..

      - name: List images
        run: docker images

      - name: Run make gen inside image
        run: docker run --userns=host --rm -v $PWD:/mnt/workspace -t libsbp-build:latest make gen
