name: Build docker image
on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - Makefile
      - .github/workflows/docker.yaml
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo chown -R "$USER:$USER" "$PWD"

          mkdir docker-build
          cd docker-build
          docker build --build-arg DOCKER_USER=$USER -f ../Dockerfile -t libsbp-build .
          cd ..

      - name: List images
        run: docker images

      - name: Run make gen inside image
        run: |
          echo $PWD
          docker run --rm --mount type=bind,source=$PWD,destination=/mnt/workspace -t libsbp-build:latest sudo mkdir .tox
